name: test

on:
  push:
    branches:
      - main
      - tests
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true

      - name: Run cross-package coverage
        run: go test -coverpkg=./... ./... -coverprofile=coverage_all.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: doors-dev/goxx
          files: coverage_all.out
